# Generated by Django 5.1.4 on 2025-09-10 18:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluk', models.CharField(blank=True, max_length=100, null=True)),
                ('village_or_city', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=50)),
                ('storage_capacity', models.PositiveIntegerField(help_text='Capacity in Kg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaddyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moisture_category', models.CharField(choices=[('Easy', 'Easy (≤13.5%)'), ('Medium', 'Medium (13.6%–15.5%)'), ('Hard', 'Hard (>15.5%)')], default='Medium', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total stock in Kg')),
                ('available_quantity', models.PositiveIntegerField(default=0, help_text='Available stock in Kg')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, help_text='₹ per Kg', max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, help_text='₹ per Kg', max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, help_text='₹ per Kg', max_digits=10)),
                ('moisture_content', models.DecimalField(decimal_places=1, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='paddy_images/')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Final avg cost per Kg', max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('stored_since', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealerprofile')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('dealer', 'name', 'moisture_category')},
            },
        ),
        migrations.CreateModel(
            name='PaddyPurchaseFromFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(blank=True, max_length=15)),
                ('paddy_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in Kg', validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_price_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='₹ per Kg', max_digits=10, null=True)),
                ('moisture_content', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total transport cost (₹)', max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, help_text='Total other costs (₹)', max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealerprofile')),
                ('paddy_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='dealer.paddystock')),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='uploads/')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in Kg', validators=[django.core.validators.MinValueValidator(1)])),
                ('moisture_content', models.DecimalField(decimal_places=1, max_digits=4)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='₹ per Kg', max_digits=10, null=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Sold', 'Sold')], default='Draft', max_length=10)),
                ('stored_since', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealerprofile')),
                ('paddy_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_posts', to='dealer.paddystock')),
            ],
        ),
    ]
