# Generated by Django 5.1.4 on 2025-09-10 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('transaction_password', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('mill_name', models.CharField(max_length=100)),
                ('mill_location', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='manager_profile/')),
                ('experience_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaddyStockOfManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddy_name', models.CharField(max_length=100)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=1, help_text='Moisture content (%)', max_digits=4, null=True)),
                ('rice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity', models.FloatField(help_text='In kg')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='paddy_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Manager's Paddy Stock",
                'verbose_name_plural': "Manager's Paddy Stocks",
            },
        ),
        migrations.CreateModel(
            name='PaymentForPaddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.marketplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_paddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.FloatField()),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=1, help_text='Moisture content (%)', max_digits=4, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Successful', 'Successful')], default='Pending', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_paddy', to='dealer.marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='RicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quality', models.CharField(max_length=100)),
                ('quantity_kg', models.FloatField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('is_sold', models.BooleanField(default=False)),
                ('rice_image', models.ImageField(blank=True, null=True, upload_to='rice_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managerPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.FloatField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_or_loss', models.FloatField(blank=True, null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRice', to='manager.ricepost')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForRice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ricepost')),
            ],
        ),
        migrations.CreateModel(
            name='RiceStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_name', models.CharField(max_length=100)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('rice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_quantity', models.FloatField(help_text='In kg')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total value of current stock', max_digits=10)),
                ('average_price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='rice_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rice Stock',
                'verbose_name_plural': 'Rice Stocks',
            },
        ),
    ]
